- name: bug
  color: d73a4a
  description: "Errores o fallos reproducibles"
- name: enhancement
  color: a2eeef
  description: "Nuevas funcionalidades o mejoras"
- name: documentation
  color: 0075ca
  description: "Cambios en la documentación"
- name: question
  color: d876e3
  description: "Preguntas o soporte"
- name: refactor
  color: cfd3d7
  description: "Mejoras de código y limpieza"
- name: needs-review
  color: f9d0c4
  description: "Requiere revisión"